# Generated by Django 2.0.8 on 2018-08-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nflgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
