# Generated by Django 2.0.8 on 2018-08-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nflgames', '0001_initial'),
        ('nflteams', '0001_initial'),
        ('userteams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpicks', to='nflgames.Game')),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpicks', to='nflteams.Team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpicks', to='userteams.UserTeam')),
            ],
        ),
    ]
